### ISSUE TITLE
nullpointer exception azure speak

### ISSUE THREAD

**Issue by WhiskerWeirdo** [WhiskerWeirdo/BanterBrain-Buddy#55]
<img width="241" alt="image" src="https://github.com/WhiskerWeirdo/BanterBrain-Buddy/assets/163717269/2a400eda-04d8-4d96-90f3-6dd123aff3c0">

```Informationen Ã¼ber das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BanterBrain_Buddy.AzureSpeechAPI.AzureSpeak(String TextToSay) in C:\Users\ar0xa\source\repos\BanterBrain Buddy\BanterBrain Buddy\AzureSpeechAPI.cs:line 205
   at BanterBrain_Buddy.SettingsForm.TTSAzureSpeakToOutput(String TextToSpeak) in C:\Users\ar0xa\source\repos\BanterBrain Buddy\BanterBrain Buddy\SettingsForm.cs:line 820
   at BanterBrain_Buddy.SettingsForm.SayTextTest(String TextToSay) in C:\Users\ar0xa\source\repos\BanterBrain Buddy\BanterBrain Buddy\SettingsForm.cs:line 904
   at BanterBrain_Buddy.SettingsForm.TestVoiceButton_Click(Object sender, EventArgs e) in C:\Users\ar0xa\source\repos\BanterBrain Buddy\BanterBrain Buddy\SettingsForm.cs:line 876
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


************** Geladene Assemblys **************```

**Comment by WhiskerWeirdo** [comment]
Seems to be related to having a selected, but inactive output device 

 _bBBlog.Debug($"SelectedOutputdevice: {outDevice.ID}");

**Comment by WhiskerWeirdo** [comment]
Throws an error now if the device ID is not a valid device
