### ISSUE TITLE
Nullpointer when enabling subscription events

### ISSUE THREAD

**Issue by WhiskerWeirdo** [WhiskerWeirdo/BanterBrain-Buddy#69]
Enabling subscription events the following nullpointer happens:

![image](https://github.com/WhiskerWeirdo/BanterBrain-Buddy/assets/163717269/87048f15-df17-4ac4-9738-6f6a24b79814)

ee the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<TwitchLib.Api.Helix.Models.EventSub.CreateEventSubSubscriptionResponse> TwitchLib.Api.Helix.EventSub.CreateEventSubSubscriptionAsync(System.String, System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>, TwitchLib.Api.Core.Enums.EventSubTransportMethod, System.String, System.String, System.String, System.String, System.String, System.String)'.
   at BanterBrain_Buddy.TwitchAPIESub.EventSubSubscribe(String type, Dictionary`2 conditions)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BanterBrain_Buddy.TwitchAPIESub.EventSubSubscribe(String type, Dictionary`2 conditions)
   at BanterBrain_Buddy.TwitchAPIESub.EventSubHandleSubscriptionGift() in C:\Users\ar0xa\source\repos\BanterBrain Buddy\BanterBrain Buddy\TwitchAPIESub.cs:line 254
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by WhiskerWeirdo** [comment]
I at least noticed the empty persona fields which is a big no-no. Added protection against that.

**Comment by WhiskerWeirdo** [comment]
Asked max for more feedback about this issue. I cannot replicate it.

**Comment by WhiskerWeirdo** [comment]
lack of feedback. if the issue persists, bug me again!
